# cross links between kernels
#admin:
#    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'

admin:
    resource: '@RzAdminBundle/Resources/config/routing/sonata_admin.xml'

_sonata_admin:
    resource: .
    type:     sonata_admin

sonata_user_admin:
    resource: '@RzUserBundle/Resources/config/routing/admin_security.xml'

sonata_user_admin_resettings:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'

sonata_media_pixlr:
    resource: '@SonataMediaBundle/Resources/config/routing/pixlr.xml'
    prefix:   /media
